[colors]
[colors.primary]
background = '#f2ecbc'
foreground = '#545464'

[colors.normal]
black   = '#545464'
red     = '#c84053'
green   = '#6f894e'
yellow  = '#77713f'
blue    = '#4d699b'
magenta = '#b35b79'
cyan    = '#597b75'
white   = '#545464'

[colors.bright]
black   = '#8a8980'
red     = '#d7474b'
green   = '#6f894e'
yellow  = '#836f4a'
blue    = '#6693bf'
magenta = '#b35b79'
cyan    = '#597b75'
white   = '#43436c'

[colors.selection]
background = '#d9d7ce'
foreground = '#43436c'

[[colors.indexed_colors]]
index = 16
color = '#cc6d00'

[[colors.indexed_colors]]
index = 17
color = '#e82424'
